In [ ]:
import numpy as np
src=[]
dst=[]
for i in range(0,4):
    src.append([float(value) for value in input(f'Enter source point{i+1} separated by a space').split(' ')])
    dst.append([float(v) for v in input(f'Enter destination point{i+1} separated by a space').split(' ')])
a = np.array([[src[0][0],src[0][1],src[0][2],1],[src[1][0],src[1][1],src[1][2],1],[src[2][0],src[2][1],src[2][2],1],[src[3][0],src[3][1],src[3][2],1]])
b = np.array([dst[0][0],dst[1][0],dst[2][0],dst[3][0]])
x = np.linalg.solve(a, b)
x=np.asmatrix(x)

c = a
d = np.array([dst[0][1],dst[1][1],dst[2][1],dst[3][1]])
y = np.linalg.solve(c, d)
y=np.asmatrix(y)

e=a
f = np.array([dst[0][2],dst[1][2],dst[2][2],dst[3][2]])
z = np.linalg.solve(e, f)
z=np.asmatrix(z)

hom_row=np.asmatrix([0.,0.,0.,1.])

k=np.concatenate((x,y,z,hom_row),0)
print('Transformation_Matrix:\n',k)
count=0
while (count<5):
    p1=input('Enter a Source point')
    p = [float(value) for value in p1.split(' ')]
    p.append(1)
    dst_p=np.matmul(k,p)
    dst_p=dst_p.tolist()
    dst_p=(dst_p[0])[:-1]
    print(dst_p)
    del p1
    del p
    count+=1

Enter source point1 separated by a space -0.09368883818387985 -0.0011555579258129 -0.18950000405311584
Enter destination point1 separated by a space -182.02 -691.82 139.33
Enter source point2 separated by a space 0.15368449687957764 0.054714057594537735 -0.2900000214576721
Enter destination point2 separated by a space -385.32 -732.75 122.02
Enter source point3 separated by a space -0.10925161838531494 -0.06905695050954819 -0.27400001883506775
Enter destination point3 separated by a space -200.49 -645.38 138.60
Enter source point4 separated by a space 0.09389473497867584 -0.06181855872273445 -0.2720000147819519
Enter destination point4 separated by a space -346.52 -646.86 121.70


Transformation_Matrix:
 [[-724.60538548   82.90733245  285.41238816 -195.72598377]
 [  18.67714179 -740.17953151   41.7580128  -683.01233701]
 [ -84.6609671    44.4134883   -11.45772205  129.27829634]
 [   0.            0.            0.            1.        ]]
