In [ ]:
import numpy as np
src=[]
dst=[]
for i in range(0,4):
    src.append([float(value) for value in input(f'Enter source point{i+1} separated by a space').split(' ')])
    dst.append([float(v) for v in input(f'Enter destination point{i+1} separated by a space').split(' ')])
a = np.array([[src[0][0],src[0][1],src[0][2],1],[src[1][0],src[1][1],src[1][2],1],[src[2][0],src[2][1],src[2][2],1],[src[3][0],src[3][1],src[3][2],1]])
b = np.array([dst[0][0],dst[1][0],dst[2][0],dst[3][0]])
x = np.linalg.solve(a, b)
x=np.asmatrix(x)

c = a
d = np.array([dst[0][1],dst[1][1],dst[2][1],dst[3][1]])
y = np.linalg.solve(c, d)
y=np.asmatrix(y)

e=a
f = np.array([dst[0][2],dst[1][2],dst[2][2],dst[3][2]])
z = np.linalg.solve(e, f)
z=np.asmatrix(z)

hom_row=np.asmatrix([0.,0.,0.,1.])

k=np.concatenate((x,y,z,hom_row),0)
print('Transformation_Matrix:\n',k)
count=0
while (count<5):
    p1=input('Enter a Source point')
    p = [float(value) for value in p1.split(' ')]
    p.append(1)
    dst_p=np.matmul(k,p)
    dst_p=dst_p.tolist()
    dst_p=(dst_p[0])[:-1]
    print(dst_p)
    del p1
    del p
    count+=1

Enter source point1 separated by a space 0.01408106368035078 0.06762700527906418 -0.242000013589859
Enter destination point1 separated by a space -140.88 -886.04 115.00
Enter source point2 separated by a space 0.06093168631196022 0.04348032921552658 -0.2410000115633011
Enter destination point2 separated by a space -174.64 -869.10 115.45
Enter source point3 separated by a space -0.021268878132104874 -0.04424624145030975 -0.24000000953674316
Enter destination point3 separated by a space -115.37 -807.23 115.31
Enter source point4 separated by a space 0.03613412752747536 -0.04424624145030975 -0.24000000953674316
Enter destination point4 separated by a space -156.63 -806.90 114.95


Transformation_Matrix:
 [[-7.18777693e+02 -4.26055170e+00 -1.87695314e+02 -1.75892986e+02]
 [ 5.74882789e+00 -7.18338609e+02 -6.74824500e+02 -1.00084940e+03]
 [-6.27144861e+00  2.20091256e+01  1.27526591e+03  4.22214266e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
