In [ ]:
import numpy as np
src=[]
dst=[]
for i in range(0,4):
    src.append([float(value) for value in input(f'Enter source point{i+1} separated by a space').split(' ')])
    dst.append([float(v) for v in input(f'Enter destination point{i+1} separated by a space').split(' ')])
a = np.array([[src[0][0],src[0][1],src[0][2],1],[src[1][0],src[1][1],src[1][2],1],[src[2][0],src[2][1],src[2][2],1],[src[3][0],src[3][1],src[3][2],1]])
b = np.array([dst[0][0],dst[1][0],dst[2][0],dst[3][0]])
x = np.linalg.solve(a, b)
x=np.asmatrix(x)

c = a
d = np.array([dst[0][1],dst[1][1],dst[2][1],dst[3][1]])
y = np.linalg.solve(c, d)
y=np.asmatrix(y)

e=a
f = np.array([dst[0][2],dst[1][2],dst[2][2],dst[3][2]])
z = np.linalg.solve(e, f)
z=np.asmatrix(z)

hom_row=np.asmatrix([0.,0.,0.,1.])

k=np.concatenate((x,y,z,hom_row),0)
print('Transformation_Matrix:\n',k)
count=0
while (count<5):
    p1=input('Enter a Source point')
    p = [float(value) for value in p1.split(' ')]
    p.append(1)
    dst_p=np.matmul(k,p)
    dst_p=dst_p.tolist()
    dst_p=(dst_p[0])[:-1]
    print(dst_p)
    del p1
    del p
    count+=1

Enter source point1 separated by a space -0.07401496917009354 -0.046586379408836365 -0.20800000429153442
Enter destination point1 separated by a space 99.16 -642.30 119.66
Enter source point2 separated by a space 0.10273104161024094 -0.04179661348462105 -0.18800000846385956
Enter destination point2 separated by a space -77.56 -647.05 138.32
Enter source point3 separated by a space 0.024583768099546432 -0.001146411057561636 -0.18800000846385956
Enter destination point3 separated by a space -1.0 -687.42 129.52
Enter source point4 separated by a space 0.07544151693582535 0.01219678483903408 -0.18800000846385956
Enter destination point4 separated by a space -50.80 -700.47 138.28


Transformation_Matrix:
 [[-9.79365051e+02  6.22173726e-01 -1.81205747e+02 -1.09894855e+01]
 [ 2.63002626e+00 -9.88050938e+02 -2.41157019e+01 -6.93151121e+02]
 [ 1.52250424e+02  7.62100894e+01 -4.30734272e+02  4.48864321e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
